#!/bin/sh

# Exit immediately for any failed (non-zero exit code) untested commands.
set -e

CMDDIR="$(dirname "$(readlink -f "$0")")"
echo "${CMDDIR}"

for command in "$(ls "${CMDDIR}/commands")"; do
  rm -f "/usr/local/sbin/${command}"
done

