#!/bin/sh

# Exit immediately for any failed (non-zero exit code) untested commands.
set -e

CMDDIR="$(dirname "$(readlink -f "$0")")"

# Do not double quote to allow globbing and word splitting.
for command in $(ls "${CMDDIR}/commands"); do
  rm -f "/usr/local/sbin/${command}"
done

