#!/bin/sh

# Exit immediately for any failed (non-zero exit code) untested commands.
set -e

CMDDIR="$(dirname "$(readlink -f "$0")")"
SRCDIR="$(echo "${CMDDIR}" | sed -e "s/commands/src/")"

. "${SRCDIR}/common.sh"
. "${SRCDIR}/config.sh"

if test_root_privileges; then
  config_rsyslog
fi

